name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.29.0/bin/windows/amd64/kubectl.exe" # or use linux binary if on Linux
          move kubectl.exe C:\kubectl.exe
          echo "C:\\" >> $env:GITHUB_PATH

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
